### ISSUE TITLE
The dropout rate

### ISSUE THREAD

**Issue by CUQS** [IDEA-opensource/DAB-DETR#11]
Thanks for your great work.
However, after reading the code, I'm confused about the setting of dropout.

The dropout rates used in the encoder and decoder layers of DAB-DETR and DAB-Deformable-DETR are set at 0.0 as default.
https://github.com/IDEA-opensource/DAB-DETR/blob/2a096e2d59fc804b20dd6da78b504654647107c7/main.py#L79-L80
https://github.com/IDEA-opensource/DAB-DETR/blob/2a096e2d59fc804b20dd6da78b504654647107c7/models/DAB_DETR/transformer.py#L459-L462
https://github.com/IDEA-opensource/DAB-DETR/blob/2a096e2d59fc804b20dd6da78b504654647107c7/models/dab_deformable_detr/deformable_transformer.py#L449-L456
DETR and Deformable-DETR use 0.1 as default, does this means training DAB-DETR or DAB-Deformable-DETR without using dropout can get better performance?

**Comment by SlongLiu** [comment]
Yes, models with 0.0 dropout tend to have better results.

**Comment by CUQS** [comment]
Thanks for your quick reply.
