### ISSUE TITLE
Architecture Changes From DINO-DETR

### ISSUE THREAD

**Issue by artest08** [IDEA-opensource/DAB-DETR#14]
Hello, 

Thanks for the great work. 

I wonder that the architecture changes such as two stage structure of DAB-Deformable-DETR (mixed query selection) which is implemented on DINO-DETR paperwork, will be also released in this repo or only in DINO-DETR page? 

Additional question is that will the DINO-DETR github repo will be based upon this repo, or will there be some drastic changes? If we start from this repo, can it be easy to move the changes of DINO training and model modifications into this repo when DINO page is released? 

Thank you so much for your responses in advance.

**Comment by SlongLiu** [comment]
We will consider providing the two-stage variant of DAB-Deformable-DETR after DINO-DETR is released. 
There will be many improvements for the DINO-DETR repo compared with this repo. But I think it is not hard to migrate the models bi-directionally.
