### ISSUE TITLE
Why does the classification head output 91 dimensionalities?

### ISSUE THREAD

**Issue by volcanolee4** [IDEA-opensource/DAB-DETR#26]
COCO only has 80 classes in object detection dataset ，why are 91 categories predicted in the code？

**Comment by SlongLiu** [comment]
The annotations in COCO have a max label id 91(although only 80 categories are used), hence we use 91 categories to follow DETR. Some label ids are blank.

**Comment by volcanolee4** [comment]
OK. Thanks for your reply!

**Comment by ASMIftekhar** [comment]
Sorry for re-opening this issue, DETR actually has 92 classes for the last classification layer. 92th (index 91) slot is used for no-object class. I see you are using 91 slots (index 0 to 90), which slot are you using to define no object?
