### ISSUE TITLE
Issue in DETRsegm

### ISSUE THREAD

**Issue by mf-skjung** [IDEA-opensource/DAB-DETR#28]
First of all, thank you very much for the great work.

My question is..

1. NotImplementError is raised when executing "self.detr.input_proj(src)" in code in DETRsegm class.

2. "self.detr.transformer(src_proj, mask, self.detr.query_embed.weight, pos[-1])"

In the code above, self.detr.query_embed is a class variable that is only initialized when use_dab=False.
I'm just curious if this is what you meant by implementation.

**Comment by SlongLiu** [comment]
We have not tested the code of DETRsegm, hence there is no quality assurance of these codes.
