### ISSUE TITLE
visualizing results

### ISSUE THREAD

**Issue by syssj1002** [IDEA-opensource/DAB-DETR#29]
Thanks for your great work.
After testing the code, how can I print the image results with bounding box?
Is there any command or code?

**Comment by yang08070201** [comment]
I want to know too！！

**Comment by lebionick** [comment]
i found `plot_dual_img` function in the code, but struggling with usage of it (no example in code at all).
So I am wondering too

**Comment by SaifeiYan** [comment]
> 
can you send the your code to me?thanks a lot!

**Comment by SaifeiYan** [comment]
> I also didn't find a visualization of outputting a single image, but I referenced DETR's visualization code, which can then be used directly here.
Are you using DAB-Deformable-DETR, can you send me the reasoning visualization file?

**Comment by SlongLiu** [comment]
Hello everyone, I provide a note for a demo of inference and visualization in https://github.com/IDEA-opensource/DAB-DETR/blob/main/inference_and_visualize.ipynb. Hope the file is helpful to you.
Thanks for your suggestions.

**Comment by SaifeiYan** [comment]
> Hello everyone, I provide a note for a demo of inference and visualization in https://github.com/IDEA-opensource/DAB-DETR/blob/main/inference_and_visualize.ipynb. Hope the file is helpful to you. Thanks for your suggestions.

Hello ,when I use your inference code, when I get to this line of code:

"output = model(image[None])
output = postprocessors['bbox'](output, torch.Tensor([[1.0, 1.0]]))[0]"
![image](https://user-images.githubusercontent.com/37232856/169734861-27085665-2d26-4279-af2f-eed1cdaad5f0.png)


![image](https://user-images.githubusercontent.com/37232856/169734781-5abd121b-7717-4aa3-ba31-d330d76fd9e5.png)

and then, how should I solve this problem, please tell me more , Thanks a lot!

**Comment by SlongLiu** [comment]
> > Hello everyone, I provide a note for a demo of inference and visualization in https://github.com/IDEA-opensource/DAB-DETR/blob/main/inference_and_visualize.ipynb. Hope the file is helpful to you. Thanks for your suggestions.
> 
> Hello ,when I use your inference code, when I get to this line of code:
> 
> "output = model(image[None]) output = postprocessors['bbox'](output, torch.Tensor([[1.0, 1.0]]))[0]" ![image](https://user-images.githubusercontent.com/37232856/169734861-27085665-2d26-4279-af2f-eed1cdaad5f0.png)
> 
> ![image](https://user-images.githubusercontent.com/37232856/169734781-5abd121b-7717-4aa3-ba31-d330d76fd9e5.png)
> 
> and then, how should I solve this problem, please tell me more , Thanks a lot!

Our code is running on CPUs, whereas the dab_deformable_detr supports GPU only.
You can send images and models to GPU before inference.
A simple way to modify it:
```python
model = model.cuda()
image = image.cuda()
output = model(image[None])
```

**Comment by SaifeiYan** [comment]
> > > Hello everyone, I provide a note for a demo of inference and visualization in https://github.com/IDEA-opensource/DAB-DETR/blob/main/inference_and_visualize.ipynb. Hope the file is helpful to you. Thanks for your suggestions.
> > 
> > 
> > Hello ,when I use your inference code, when I get to this line of code:
> > "output = model(image[None]) output = postprocessors['bbox'](output, torch.Tensor([[1.0, 1.0]]))[0]" ![image](https://user-images.githubusercontent.com/37232856/169734861-27085665-2d26-4279-af2f-eed1cdaad5f0.png)
> > ![image](https://user-images.githubusercontent.com/37232856/169734781-5abd121b-7717-4aa3-ba31-d330d76fd9e5.png)
> > and then, how should I solve this problem, please tell me more , Thanks a lot!
> 
> Our code is running on CPUs, whereas the dab_deformable_detr supports GPU only. You can send images and models to GPU before inference. A simple way to modify it:
> 
> ```python
> model = model.cuda()
> image = image.cuda()
> output = model(image[None])
> ```
Thank you very much for the answer, I also solved the problem, wish you success in your career, thanks again

**Comment by yang08070201** [comment]
I find this code will inference validation dataset，but I don‘t konw how to inference local pictures.

**Comment by lebionick** [comment]
Use PIL Image with path to your image and None as target

**Comment by SlongLiu** [comment]
I update the notebook to support visualize custom images. See https://github.com/IDEA-opensource/DAB-DETR/blob/main/inference_and_visualize.ipynb for more details. 

> I find this code will inference validation dataset，but I don‘t konw how to inference local pictures.
