### ISSUE TITLE
What's the performance when `rm_self_attn_decoder` set to `True`?

### ISSUE THREAD

**Issue by ZHANGHeng19931123** [IDEA-opensource/DAB-DETR#3]
Hello, I noticed that in https://github.com/IDEA-opensource/DAB-DETR/blob/94f20eda2be7cf38ddf94102db92e949b6846a65/models/DAB_DETR/transformer.py#L333 , there is a parameter `rm_self_attn_decoder` that is set to `False` by default.
Have you ever set it to True? What's the performance?

**Comment by SlongLiu** [comment]
We found the performance droped a lot without self-attntention in decoder layers.
