### ISSUE TITLE
The feature dim mismatch?

### ISSUE THREAD

**Issue by Rain-coder1** [IDEA-opensource/DAB-DETR#32]
https://github.com/IDEA-opensource/DAB-DETR/blob/309f6ad92af7a62d7732c1bdf1e0c7a69a7bdaef/models/DAB_DETR/transformer.py#L446
In this place, the last dim of tgt2 is 2*256, while the tgt's last dim is 256, so it will cause a mismatch error?

**Comment by SlongLiu** [comment]
Actually, it won't. The last dim of tgt2 is 256 as well. we use the first 256 dimensions of positional encoded anchors for cross-attention modules.
