### ISSUE TITLE
can i train dab-deformable-detr with multi-gpu in one machine?

### ISSUE THREAD

**Issue by nvilli** [IDEA-opensource/DAB-DETR#33]
i've tried to train dab-deformable-detr with multi-gpus in one ubuntu server by using  'torch.nn.Parallel', but a runtime error raised which is "Expected tensor for augment #1 'input' to have the same device as tensor for argument #2 'weight'; but device 0 does not equal 1(while checking arguments for cudnn_convolution)". Is this a bug? Or there is any other way to train dab-deformable-detr with multi-gpus?

**Comment by lebionick** [comment]
why don't you use training script from the repo?
```
# for dab_deformable_detr: 48.1 AP
python -m torch.distributed.launch --nproc_per_node=8 \
  main.py -m dab_deformable_detr \
  --output_dir logs/dab_deformable_detr/R50 \
  --batch_size 2 \
  --epochs 50 \
  --lr_drop 40 \
  --transformer_activation relu \
  --coco_path /path/to/your/COCODIR
```

**Comment by SlongLiu** [comment]
Thanks for the reply of @lebionick. It is the correct answer to the question.

**Comment by CScgy** [comment]
> why don't you use training script from the repo?
> 
> ```
> # for dab_deformable_detr: 48.1 AP
> python -m torch.distributed.launch --nproc_per_node=8 \
>   main.py -m dab_deformable_detr \
>   --output_dir logs/dab_deformable_detr/R50 \
>   --batch_size 2 \
>   --epochs 50 \
>   --lr_drop 40 \
>   --transformer_activation relu \
>   --coco_path /path/to/your/COCODIR
> ```
> 
> it worked for me

In one GPU of 64GB memory it's ok, but I used torch.distributed.launch in 4 GPUs, each of 24GB memory, and memory of all GPUs are fully occupied when the program starts, causing CUDAOutOfMemory error. How can I solve this problem?
