### ISSUE TITLE
About parameter bbox_embed_diff_each_layer in DABDETR.py.

### ISSUE THREAD

**Issue by lmc8133** [IDEA-opensource/DAB-DETR#34]
model/DAB_DETR/DABDETR.py line 85 should be
 "bbox_embed_diff_each_layer: dont share weights of prediction heads. Default for False.(shared weights.)" 
rather than the origin  "Default for True".  So it consistent with line 72.
 Am I right?

**Comment by SlongLiu** [comment]
Thanks for your question. You are right and it is a typo in our codes.
