### ISSUE TITLE
cat(y, x) in gen_sineembed_for_position()

### ISSUE THREAD

**Issue by yyccli** [IDEA-opensource/DAB-DETR#36]
Hi, first thanks for your great work to improve DETR-like detectors!
I have a question on the cat() operation when we want to get query pos embedding using func `gen_sineembed_for_position()` in file `models/DAB_DETR/transformer.py` line 51 and 61. Why here use 
```
pos = torch.cat((pos_y, pos_x)...)
```

should `x` come first than `y` ?

**Comment by SlongLiu** [comment]
Our design aims to be consistent with the positional encoding of image features. as shown in https://github.com/IDEA-opensource/DAB-DETR/blob/main/models/DAB_DETR/position_encoding.py#L58, the order is ```pos_y``` followed by ```pos_x```.

**Comment by yyccli** [comment]
Hi, thank you for your reply. I understand now.
