### ISSUE TITLE
ImportError: cannot import name 'test' from 'engine'

### ISSUE THREAD

**Issue by Ixiaohuihuihui** [IDEA-opensource/DAB-DETR#4]
It seems that 'engine.py' doesn't conclude the test function.

**Comment by SlongLiu** [comment]
Thanks for your issues. The bug has been fixed just now.

**Comment by Ixiaohuihuihui** [comment]
Thank you, I have received the e-mail! I will reply as soon as possible——Linhui Dai

**Comment by Ixiaohuihuihui** [comment]
OK, just delete the test in main.py 🤣
`from engine import evaluate, train_one_epoch`
