### ISSUE TITLE
Bad testing results

### ISSUE THREAD

**Issue by Aliweka2020** [IDEA-opensource/DAB-DETR#40]
I run the model with the default setting and got bad results

any suggestions .....

![image](https://user-images.githubusercontent.com/6129944/171649102-2c189be2-85f6-4439-829d-0dc5a7716c25.png)

![image](https://user-images.githubusercontent.com/6129944/171649399-cdf71267-6e3b-4f26-86b9-0ffff5d89568.png)

**Comment by SlongLiu** [comment]
I provide an example to visualize custom images in https://github.com/IDEA-opensource/DAB-DETR/blob/main/inference_and_visualize.ipynb. Hope this file is helpful.
