### ISSUE TITLE
Num_patterns in dab deformable detr

### ISSUE THREAD

**Issue by artest08** [IDEA-opensource/DAB-DETR#42]
Thanks for the great contribution to the literature. 

I have a quick question. Is there a specific reason for not using pattern embedding in dab-deformable-detr? Is pattern embedding not applicable to deformable structure? Maybe it might not increase the performance of dab-detr but I havent seen any ablation study related with that. 

Thanks in advance

**Comment by SlongLiu** [comment]
Thanks for your questions. We find the pattern embedding not helpful to the final performance of dab-deformable-detr. We use it in the standard dab-detr where it introduces gains.
