### ISSUE TITLE
Twostage deformable detr and dab

### ISSUE THREAD

**Issue by Ixiaohuihuihui** [IDEA-opensource/DAB-DETR#5]
Can't two stage and use DAB be set to true at the same time?
`if self.two_stage:
...`

`elif self.use_dab:
...`

**Comment by SlongLiu** [comment]
As shown in our paper, we did not test the two-stage variant of our DAB-Deformable-DETR.

**Comment by SlongLiu** [comment]
Even so, our DAB-Deformable-DETR has outperformed the two-stage Deformable DETR with a large margin. A new PR to support two-stage DAB-Deformable-DETR is welcome.
