### ISSUE TITLE
What is the purpose of the minus of max attention weight

### ISSUE THREAD

**Issue by JosonChan1998** [IDEA-opensource/DAB-DETR#8]
Hi, thanks for you nice work! 

But I have a confuse about the code.What is the purpose of the minus of max attention weight？

https://github.com/IDEA-opensource/DAB-DETR/blob/9b637396d2d8eea16b39940cde8e7d34262cb2e2/models/DAB_DETR/attention.py#L381-L382

Looking for your reply!

**Comment by SlongLiu** [comment]
Thanks for your question. It is a trick to stable the training but not affect the final results.

**Comment by JosonChan1998** [comment]
Thanks for your reply.

I want to ask another question about the affect of query pos in decoder layer. In the decoder layer, the query pos is used for self attn and cross attn.  So have you done an ablation study about the affect of the query pos just in self attn or cross attn?

**Comment by SlongLiu** [comment]
I did not do some ablations about the query pos in decoder layers, including both self-attn and cross-attn. However, as our paper shows the importance of the formulation of query pos, I think they have a large impact on the final performance.

**Comment by JosonChan1998** [comment]
ok! Thanks for your relpy!
